# please make sure that ports starts from 4xxx (just for my machine)!
# please make sure that volumes starts from stu4 (just for my machine)!
# here is a example
version: '2.8'
services:
  hhb2023:
    hostname: hhb2023
    container_name: hhb2023
    user: 1004:1004
    build: ..
    image: wxl2080ti:0.1.0
    runtime: nvidia  # 使用NVIDIA Docker runtime
    ports:
      - "4022:22"
      - "4591:5902"
      - "4088:8888"
      - "4666:6006"
    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data/stu4/workspace:/home/stu/workspace  # 挂载工作目录
      - ./data/stu4/envs/:/opt/anaconda/envs
      - ./data/stu4/conf/apt:/etc/apt
    environment:
      # - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all  # 使用所有可见的NVIDIA设备
    privileged: true
    shm_size: 32gb
    stdin_open: true
    tty: true
